"""MegaPersona schema, sampling, survey, and validation utilities."""

from src.mega_persona.evaluation import (
    MegaPersonaEvaluation,
    evaluate_mega_personas,
    personas_to_axis_matrix,
)
from src.mega_persona.consistency import (
    ConsistencyIssue,
    PersonaConsistencyReport,
    PopulationConsistencyEvaluation,
    evaluate_persona_consistency,
    evaluate_population_consistency,
)
from src.mega_persona.experiment import (
    MegaPersonaExperimentConfig,
    MegaPersonaExperimentRun,
    MegaPersonaExperimentRunner,
    MegaPersonaExperimentSummary,
    compute_experiment_score,
    write_experiment_artifacts,
)
from src.mega_persona.evolution import (
    EVOLUTION_PROMPT_OPERATORS,
    MegaEvolutionCandidate,
    MegaEvolutionConfig,
    MegaPersonaEvolver,
    build_run_manifest,
    blueprint_from_slot,
    candidate_slots,
    default_genome,
    default_genome_v4,
    mutate_genome,
    mutate_genome_v4,
    prompt_addendum_from_genome,
)
from src.mega_persona.generator import (
    AgentOutputError,
    MegaPersonaGenerationResult,
    MegaPersonaGenerator,
    parse_json_object,
)
from src.mega_persona.openevolve_adapter import (
    MegaGenomeMutator,
    MegaOpenEvolveEvaluator,
    MegaPersonaOpenEvolveRunner,
    genome_from_code,
    genome_hash,
    genome_to_code,
    open_evolve_fitness_from_payload,
)
from src.mega_persona.schema import MegaPersona
from src.mega_persona.shadow_survey import (
    SCIENTIFIC_SCALE_REGISTRY,
    ShadowSurvey,
    ShadowSurveyItem,
    ShadowSurveySplit,
    build_initial_shadow_surveys,
    build_shadow_survey_splits,
    read_shadow_survey_splits,
    score_shadow_survey,
    shadow_survey_split_hashes,
    write_shadow_survey_splits,
)
from src.mega_persona.shadow_simulator import (
    ConcordiaNativeShadowSimulator,
    ConcordiaShadowSimulator,
    LLMShadowSimulator,
    ShadowBehaviorReport,
    ShadowSurveySimulation,
    StudentRealisticShadowSimulator,
    StudentRealisticV2ShadowSimulator,
    aggregate_shadow_behavior,
    build_shadow_simulator,
    shadow_behavior_axis_matrix,
)
from src.mega_persona.slots import (
    AXIS_NAMES,
    AXIS_ROLE_MAP,
    LEGACY_AXIS_TO_ROLE,
    MegaPersonaSlot,
    QuotaBucket,
    SlotSampler,
    axis_names_for_binding,
    axis_roles_for_binding,
    axis_roles_for_target_axes,
    build_adaptive_constraints,
    default_schema_binding,
    quota_buckets_for_binding,
    schema_binding_for_genome,
)
from src.mega_persona.html_viz import generate_html_report
from src.mega_persona.template_generator import RuleBasedMegaPersonaBuilder
from src.mega_persona.validator import ValidationIssue, ValidationReport, validate_mega_persona
from src.mega_persona.visualization import visualize_result_path

__all__ = [
    "AXIS_NAMES",
    "AXIS_ROLE_MAP",
    "AgentOutputError",
    "EVOLUTION_PROMPT_OPERATORS",
    "MegaPersonaEvaluation",
    "MegaPersonaExperimentConfig",
    "MegaPersonaExperimentRun",
    "MegaPersonaExperimentRunner",
    "MegaPersonaExperimentSummary",
    "MegaGenomeMutator",
    "MegaOpenEvolveEvaluator",
    "MegaEvolutionCandidate",
    "MegaEvolutionConfig",
    "MegaPersonaEvolver",
    "MegaPersonaOpenEvolveRunner",
    "MegaPersonaGenerationResult",
    "ConcordiaNativeShadowSimulator",
    "ConcordiaShadowSimulator",
    "ConsistencyIssue",
    "LLMShadowSimulator",
    "MegaPersonaGenerator",
    "MegaPersona",
    "MegaPersonaSlot",
    "PersonaConsistencyReport",
    "PopulationConsistencyEvaluation",
    "QuotaBucket",
    "RuleBasedMegaPersonaBuilder",
    "SCIENTIFIC_SCALE_REGISTRY",
    "ShadowBehaviorReport",
    "ShadowSurvey",
    "ShadowSurveyItem",
    "ShadowSurveySplit",
    "ShadowSurveySimulation",
    "SlotSampler",
    "StudentRealisticShadowSimulator",
    "StudentRealisticV2ShadowSimulator",
    "aggregate_shadow_behavior",
    "axis_names_for_binding",
    "axis_roles_for_binding",
    "axis_roles_for_target_axes",
    "build_shadow_simulator",
    "ValidationIssue",
    "ValidationReport",
    "build_adaptive_constraints",
    "build_initial_shadow_surveys",
    "build_shadow_survey_splits",
    "read_shadow_survey_splits",
    "build_run_manifest",
    "blueprint_from_slot",
    "candidate_slots",
    "compute_experiment_score",
    "default_genome",
    "default_genome_v4",
    "default_schema_binding",
    "evaluate_mega_personas",
    "evaluate_persona_consistency",
    "evaluate_population_consistency",
    "generate_html_report",
    "genome_from_code",
    "genome_hash",
    "genome_to_code",
    "mutate_genome",
    "mutate_genome_v4",
    "open_evolve_fitness_from_payload",
    "prompt_addendum_from_genome",
    "quota_buckets_for_binding",
    "parse_json_object",
    "personas_to_axis_matrix",
    "score_shadow_survey",
    "schema_binding_for_genome",
    "shadow_behavior_axis_matrix",
    "shadow_survey_split_hashes",
    "validate_mega_persona",
    "visualize_result_path",
    "write_shadow_survey_splits",
    "write_experiment_artifacts",
]
